### PR TITLE
Change hashtag in README.md

### PR DESCRIPTION
**Pull request by thebergamo**
Using #nodeschool-day instead #nodeschool-int for more semantic hashtag

### CODE REVIEW

**Comment by iancrowther** [comment]
I'd like to reject this PR based on the following comment

https://github.com/nodeschool/international-day/issues/98#issuecomment-168435800

take a look..

https://twitter.com/search?q=%23international-day&src=typd

**Comment by iancrowther** [comment]
thats for the PR btw! I do apreciate it..

**Comment by thebergamo** [comment]
This is the search using #nodeschool-day

https://twitter.com/search?q=%23nodeschool-day&src=typd

**Comment by jeduan** [comment]
Just throwing my 0.02: I like #nodeschool-day more than #nodeschool-int. Feel like it's easier to understand if you don't know anything about what's going on.

**Comment by thebergamo** [comment]
@iancrowther what you think?

**Comment by iancrowther** [comment]
thanks @thebergamo

**Comment by TylerMoeller** [comment]
This probably needs to be thought through some more. Hashtags cannot include punctuation, like the hyphen in `#nodeschool-day`. The hashtag ends up getting categorized under `#nodeschool`. 

From: https://support.twitter.com/articles/370610

>  Is there a symbol or punctuation in or after the hashtag? If you write #it'ssotasty, your message will be categorized under #it. Punctuation marks ( , . ; ' ? ! etc.) will end your hashtag wherever punctuation occurs.

**Comment by thebergamo** [comment]
hum... @TylerMoeller nice point! What @iancrowther say about using camelCase?

#nodeschoolDay ?

**Comment by riyadhalnur** [comment]
As far as I know, hastags are case-insensitive on Twitter

**Comment by thebergamo** [comment]
well, `#nodeschoolday` is the only solution I guess

**Pull request merged**
