### PR TITLE
added more enrollment info

### PR DESCRIPTION
**Pull request by iancrowther**

### CODE REVIEW

**Comment by Sequoia** [comment]
What does this mean, practically speaking? "No new users in @nodeschool/owners 'til after the 23rd"? I mean anyone can add a chapter/event & push it to nodeschool.io, yes? I think this is _probably_ a nonissue, events will happen where they happen, fall thru where the fall thru & that's OK.

Perhaps an issue could be opened next Monday or so on chapter repos asking organizers to verify that their event is online & then Friday events list could be cleaned up based on negative or absent responses? This _would_ improve the integrity of the events list, but OTOH it's extra work & again it's not really a big deal if the lists isn't 100% accurate. Thoughts?
(This would be a good task for someone not busy organizing an event).

**Comment by martinheidegger** [comment]
@Sequoia In my understanding enrollment comes with responsibilities. (see [PARTICIPATING.md](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md)) People that didn't sign up by the deadline can not take on the responsibilities. In other words: even when they hold an event that day, they will not be part of the international call, not listed on the homepage, etc.

**Comment by iancrowther** [comment]
A chapter can indeed still run an event, but it wont be included in the international day.  We just need a sensible cut off for admin reasons.

**Comment by Sequoia** [comment]
> In my understanding enrollment comes with responsibilities. (see PARTICIPATING.md)

lol didn't you _write_ that document? :smile_cat: anyway yeah seems fair enough. one question: how to add sticker to hexdex.

**Comment by ghost** [comment]
@Sequoia fork [nodeschool/nodeschool.github.io](https://github.com/nodeschool/nodeschool.github.io), add your chapter hexagon under `/images/`, add the corresponding HTML in `/hexdex.html` and you should be good to go for a PR.

**Comment by Sequoia** [comment]
tyvm @kytwb! /cc @a-pasquale

**Pull request merged**
